### ISSUE TITLE
Regression: get_entity_fields() is being called on taxonomy terms and is failing.

### ISSUE THREAD

**Issue by rosiel** [mjordan/islandora_workbench#345]
Since pulling changes `042e5d9..c2a8e82` I have been getting the following error:

`Error: Workbench cannot retrieve field definitions from Drupal. Please confirm that the Field, Field Storage, and Entity Form Display REST resources are enabled.`

It was calling get_entity_fields() with entity_type='taxonomy term', which hadn't happened before. The response was a 404 with message `b'{"message":"The \\u0022entity_form_display\\u0022 parameter was not converted for the path \\u0022\\/entity\\/entity_form_display\\/{entity_form_display}\\u0022 (route name: \\u0022rest.entity.entity_form_display.GET\\u0022)"}'`. 

I notice in the comparison that there was a warning, to the extent of "This is known to fail with 404 on taxonomy vocabularies without extra fields configured." that was also removed within these commits.

https://github.com/mjordan/islandora_workbench/compare/042e5d98c7aba1a9f7078179e98d3a21defbeaf9...c2a8e82

**Comment by mjordan** [comment]
Sorry @rosiel, I didn't do a very good job of resolving a set of merge conflicts I was wrestling with. They are resolved now. I'll be posting a message about some of the changes in the #islandoraworkbench slack channel.

**Comment by rosiel** [comment]
I've tried the latest code on `main` and i'm still getting a 404 when calling get_entity_fields on a vocabulary that has no extra fields:
<img width="1680" alt="Screen Shot 2021-11-01 at 3 45 39 PM" src="https://user-images.githubusercontent.com/1943338/139725040-8646c1f5-e3e4-4fcc-9b1b-8f09760544a6.png">

**Comment by mjordan** [comment]
Can you confirm that the "Entity form display" REST resource is enabled in your target Drupal (/admin/config/services/rest)?

**Comment by mjordan** [comment]
As discussed in slack, I suspect https://github.com/mjordan/islandora_workbench/blob/cf250ea3aefcc713cb0e78d989b08aeec147bdf3/workbench_utils.py#L639 is the key to success here.

**Comment by mjordan** [comment]
@rosiel please pull in changes to main branch and try again.

**Comment by mjordan** [comment]
@rosiel even though I've fixed this in `main` if you could confirm I actually fixed it, we can close this.

**Comment by mjordan** [comment]
@rosiel OK to close this?

**Comment by rosiel** [comment]
Yes! Many many thanks @mjordan
